{{- if .Values.config }}
apiVersion: v1
data:
  config.yaml: |
    {{- if .Values.config.repos }}
    repos:
    {{- range $repo := .Values.config.repos }}
      - name: {{ $repo.name }}
        bucket: {{ $repo.bucket }}
    {{- end }}
    {{- end }}
    {{- if .Values.config.storage }}
    storage:
      {{- if .Values.config.storage.s3 }}
      s3:
        bucket: {{ .Values.config.storage.s3.bucket }}
        region: {{ .Values.config.storage.s3.region }}
        {{- if .Values.config.storage.s3.protocol }}
        protocol: {{ .Values.config.storage.s3.protocol }}
        {{- end }}
      {{- end }}
      {{- if .Values.config.storage.swift }}
      swift:
        username: {{ .Values.config.storage.swift.username }}
        password: {{ .Values.config.storage.swift.password }}
        tenant: {{ .Values.config.storage.swift.tenant }}
        authUrl: {{ .Values.config.storage.swift.authUrl }}
        endpointType: {{ .Values.config.storage.swift.endpointType }}
        container: {{ .Values.config.storage.swift.container }}
        insecureSkipVerify: {{ .Values.config.storage.swift.insecureSkipVerify }}
      {{- end }}
      {{- if .Values.config.storage.gcs }}
      gcs: {{ .Values.config.storage.gcs }}
      {{- end }}
    {{- end }}

kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-publisher-config
  namespace: {{ .Release.Namespace }}
{{- end }}
