{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "helm-chart-publisher.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Release.Name }}.{{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "helm-chart-publisher.fullname" . }}
          servicePort: {{ .Values.service.port }}
  tls:
  - hosts:
    - {{ .Release.Name }}.{{ .Values.ingress.host }}
{{- end }}
